[project]
name = "pylontech-exporter"
version = "0.1.0"
description = "Prometheus Exporter for polyntech US2000C battery"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "prometheus-client==0.20.0",
    "pyserial==3.5",
]
