name: "Build ci image"

on: 
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}/ci-image

jobs:
  build:
    runs-on: [self-hosted]
    permissions:
      contents: read
    steps: 
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Check env
        run: |
          pwd
          id
          printenv
          ls -alh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."${{ secrets.REGISTRY_HOST }}"]
            http = false
            insecure = false
            ca = ["/ca-cert.crt"]

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Get Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.REGISTRY_HOST }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest

      # type=raw,value=${{ steps.generate-docker-tag.outputs.DOCKER_TAG }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .github
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Clean up docker images
        run: |
          docker image prune -af